[window]
opacity = 0.9

  [window.padding]
  x = 8
  y = 8

[font]
size = 14

  [font.normal]
  family = "FiraCode Nerd Font"
  style = "Medium"

[colors.primary]
background = "#1b1b25"
foreground = "#dedede"

[colors.normal]
black = "#15121c"
red = "#cb5760"
green = "#999f63"
yellow = "#d4a067"
blue = "#6c90a8"
magenta = "#776690"
cyan = "#528a9b"
white = "#eeffff"

[colors.bright]
black = "#727480"
red = "#cb5760"
green = "#999f63"
yellow = "#d4a067"
blue = "#6c90a8"
magenta = "#776690"
cyan = "#528a9b"
white = "#eeffff"
